POST http://localhost:8081/api/users/
Content-Type: application/json

{
  "username": "test2",
  "password": "123123",
  "checkPassword": "123123",
  "koreanName": "123",
  "englishName": "13",
  "userStatus": "ATTENDING",
  "authorityType": "MANAGER",
  "activeStatus": "ACTIVE",
  "userType": "C_FULL_TIME_MS",
  "gender": "MALE"
}